# Generated by Django 5.0.6 on 2024-07-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Programming Languages', 'Programming Languages'), ('Web Development', 'Web Development'), ('Frameworks/Libraries', 'Frameworks/Libraries'), ('Technologies', 'Technologies')], max_length=50)),
            ],
        ),
    ]
