# Generated by Django 5.0.6 on 2024-07-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_experience_responsibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('start_year', models.CharField(max_length=100)),
                ('end_year', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField()),
            ],
        ),
    ]
